# Generated by Django 5.1.6 on 2025-03-11 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('Issue_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Issue_Type', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('SupportFile', models.FileField(blank=True, null=True, upload_to='issue_support_files/')),
                ('Status', models.CharField(default='Open', max_length=50)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
                ('Assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to='accounts.lecturer')),
                ('Department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_issues', to='accounts.department')),
                ('Lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturer_issues', to='accounts.lecturer')),
                ('Registrar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrar_issues', to='accounts.academicregistrar')),
                ('Student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_issues', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('Notification_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Message', models.TextField()),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_notifications', to='issues.issue')),
                ('Lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturer_notifications', to='accounts.lecturer')),
                ('Registrar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrar_notifications', to='accounts.academicregistrar')),
                ('Student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_notifications', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
    ]
