# Generated by Django 5.2 on 2025-04-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='registrar_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
