# Generated by Django 5.1.5 on 2025-04-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='institutional_email',
            field=models.EmailField(default=None, max_length=50, unique=True),
        ),
    ]
