# Generated by Django 5.2 on 2025-04-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_registrar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
